import fs from 'fs';
let code = fs.readFileSync('src/services/api.ts', 'utf8');

code = code.replace(/const FALLBACK_PROMPTS = \[[\s\S]*?\];/, '');
code = code.replace(/return FALLBACK_PROMPTS;/g, 'return _FALLBACK_PROMPTS;');

const topLevelArray = `
const _FALLBACK_PROMPTS = [
  "Build a scalable microservices architecture in Go",
  "Design an event-driven architecture using Kafka",
  "How to become a Senior Frontend Engineer",
  "Learning roadmap for Rust programming",
  "Full-stack Web3 and Blockchain developer guide",
  "Step-by-step guide to becoming a Data Scientist",
  "Architect a highly available Cloud-native app on AWS",
  "Mastering Kubernetes and Container Orchestration",
  "Roadmap to passing the AWS Solutions Architect exam",
  "How to build an AI chatbot using LLMs and RAG",
  "Design a real-time multiplayer game server",
  "Learning path for a UX/UI Product Designer",
  "Complete guide to becoming a DevOps Engineer",
  "How to build your own custom mechanical keyboard",
  "Roadmap to becoming a certified Welder",
  "Step-by-step guide to building a tiny house",
  "How to start a successful podcast from scratch",
  "Learning path for a professional Video Editor",
  "Mastering AutoCAD for Civil Engineering",
  "How to design a sustainable eco-friendly home",
  "Roadmap for a career in Cyber Security",
  "Guide to becoming a licensed Electrician",
  "Learning path for a 3D Modeler & Animator",
  "How to restore a classic muscle car",
  "Step-by-step guide to writing a novel",
  "Roadmap to becoming a professional Chef",
  "How to build a SaaS startup as a solo founder",
  "Learning path for a Financial Analyst",
  "Guide to starting a dropshipping e-commerce business",
  "Mastering SEO and Digital Marketing",
  "How to create a viral social media campaign",
  "Roadmap to becoming a Registered Nurse",
  "Guide to passing the CPA exam",
  "How to brew your own craft beer at home",
  "Learning path for a Real Estate Agent",
  "Step-by-step guide to creating a graphic novel",
  "Roadmap for becoming an Airline Pilot",
  "How to build a smart home automation system",
  "Guide to urban farming and hydroponics",
  "Learning path for a Fitness Personal Trainer",
  "Roadmap to becoming a freelance Copywriter",
  "How to plan and launch a Kickstarter campaign",
  "Mastering machine learning with Python",
  "Guide to becoming a professional Photographer",
  "How to build a high-performance gaming PC",
  "Roadmap for a career in Game Development",
  "Learning path for an iOS Swift Developer",
  "Guide to becoming a commercial Drone Pilot",
  "How to start a food truck business",
  "Roadmap for becoming a Yoga Instructor",
  "Mastering public speaking and presentations",
  "Guide to investing in cryptocurrency",
  "How to build a personal brand on LinkedIn",
  "Roadmap for becoming a Product Manager",
  "Learning path for a Database Administrator",
  "Guide to creating a successful YouTube channel",
  "How to start a sustainable clothing brand",
  "Roadmap to becoming a Sommelier",
  "Mastering prompt engineering for AI models",
  "Guide to becoming a licensed Plumber",
  "How to write and direct a short film",
  "Roadmap for a career in Renewable Energy",
  "Learning path for a Quantum Computing researcher",
  "Guide to becoming a professional eSports gamer",
  "How to start a nonprofit organization",
  "Roadmap to becoming an Interior Designer",
  "Mastering the art of woodworking and carpentry",
  "Guide to becoming a successful day trader",
  "How to build a mobile app in React Native",
  "Roadmap for a career in Biomedical Engineering",
  "Learning path for a 2D Concept Artist",
  "Guide to becoming a Travel Blogger",
  "How to start a wedding planning business",
  "Roadmap to becoming a Veterinary Technician",
  "Mastering digital music production (Ableton)",
  "Guide to becoming a certified Scuba Instructor",
  "How to build a solar-powered generator",
  "Roadmap for a career in Marine Biology",
  "Learning path for an Agile Scrum Master",
  "Guide to becoming a professional Makeup Artist",
  "How to publish a board game",
  "Roadmap to becoming a Voice Over Actor",
  "Mastering the art of pottery and ceramics",
  "Guide to becoming a Private Investigator",
  "How to start a pet grooming business",
  "Roadmap for a career in Aerospace Engineering",
  "Learning path for a Technical Writer",
  "Guide to becoming a certified translator",
  "How to build a successful Patreon community",
  "Roadmap to becoming a Landscape Architect",
  "Mastering foreign exchange (Forex) trading",
  "Guide to becoming a professional DJ",
  "How to start a successful baking business",
  "Roadmap for a career in Artificial Intelligence",
  "Learning path for a CNC Machinist",
  "Guide to becoming an Event Planner",
  "How to build a community garden",
  "Roadmap to becoming a Blockchain Auditor",
  "Mastering negotiation and sales techniques",
  "Guide to becoming a professional Astrologer",
  "How to start a boutique coffee shop",
  "Roadmap for a career in Music Therapy"
];

export const api = {
`;

code = code.replace(/export const api = \{/, topLevelArray);
fs.writeFileSync('src/services/api.ts', code);
console.log('Fixed api.ts');
