export type UserRole = 'user' | 'creator' | 'admin';
export type BlueprintSource = 'official' | 'creator' | 'ai_generated' | 'remixed';

export interface User {
  id: string;
  name: string;
  email: string;
  avatar: string;
  role: UserRole;
  isCreatorSubscriptionActive: boolean;
  creatorSubscriptionId?: string; // Sub ID for external providers like Stripe
  walletBalance: number;
  stripeAccountId?: string; // For creator payouts
  createdAt: string;
  updatedAt: string;
}

export interface Blueprint {
  id: string;
  title: string;
  slug: string;
  description: string;
  domain: string;
  price: number;
  isFree: boolean;
  rating: number;
  starsCount: number;
  techStack: string[];
  
  // Publishing and origin metadata
  creatorId: string;
  source: BlueprintSource;
  originalBlueprintId?: string; // If this was remixed from another blueprint
  isPublished: boolean;
  version: string;
  
  // Data Privacy & AI Tracking
  allowDataTraining: boolean; // false if generated by a 'creator' to protect copyright
  aiPromptUsed?: string; // If ai_generated, the prompt that created it
  
  nodesCount: number;
  createdAt: string;
  updatedAt: string;

  // Populated relation for UI convenience
  creator: {
    name: string;
    avatar: string;
  };
}

export type NodeType = 'task' | 'service' | 'db' | 'decision' | 'ai' | 'trigger';
export type NodeStatus = 'pending' | 'in_progress' | 'completed';

export interface FlowchartNode {
  id: string;
  blueprintId: string;
  label: string;
  description?: string;
  type: NodeType;
  status: NodeStatus;
  codeSnippet?: string;
  docsUrl?: string;
  position?: { x: number; y: number };
  customData?: Record<string, any>; // Used for editable formatting or custom node props
  
  // AI tracking per node
  isAiGenerated: boolean;
  allowDataTraining: boolean; 
}

export interface FlowchartEdge {
  id: string;
  blueprintId: string;
  sourceId: string;
  targetId: string;
  label?: string;
  animated?: boolean;
}

export interface Transaction {
  id: string;
  buyerId: string;
  creatorId: string;
  blueprintId: string;
  amount: number;
  platformFee: number;
  creatorEarnings: number;
  status: 'completed' | 'pending' | 'failed';
  paymentMethod?: string;
  stripePaymentIntentId?: string;
  createdAt: string;
}

export interface CreatorPayout {
  id: string;
  creatorId: string;
  amount: number;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  stripeTransferId?: string;
  createdAt: string;
  completedAt?: string;
}

export interface UserProgress {
  userId: string;
  blueprintId: string;
  completedNodeIds: string[];
  percentage: number;
  lastAccessedAt: string;
}

export interface AIGenerationLog {
  id: string;
  userId: string;
  userRoleAtGeneration: UserRole;
  prompt: string;
  generatedBlueprintId?: string;
  generatedNodeIds?: string[];
  allowDataTraining: boolean; // Must be false if userRoleAtGeneration === 'creator'
  createdAt: string;
}